- name: Initialize the cluster
  become: yes
  shell: kubeadm init

- name: Create .kube directory
  become_user: ec2-user
  file:
    path: "~/.kube"
    state: directory
    mode: 0777

- name: Copies admin.conf to user's kube config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ec2-user/.kube/config
    remote_src: yes
    owner: ec2-user
    mode: 0644

- name: Install Pod network
  become: yes
  become_user: ec2-user
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  args:
    chdir: /home/ec2-user






